#ifndef __ATSIM_CONFIG
#define __ATSIM_CONFIG

#define MCU_ATTiny85

// #define DEBUG_PRINT_PC
// #define DEBUG_PRINT_MNEMONICS
// #define DEBUG_PRINT_OPERANDS
// #define DEBUG_TRACE_MEMORY_ACCESSES
// #define DEBUG_LIMIT_CLOCK_RATE_HZ 100
// #define DEBUG_STACK_COLLISION_DETECTION 0x98

#define USI_CHARACTER_OUTPUT

#endif
