name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      -name: Install avr-gcc
        run: sudo apt-get install -y avr-libc

      -name: Install binutils-avr
        run: sudo apt-get install -y binutils-avr

      -name: Install gcc-avr
        run: sudo apt-get install -y gcc-avr

      - name: Make project
        run: make

      - name: Test project
        run: make test
